version: '3'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  bffproductservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

